In [17]:
import os

print("Access Key:", os.getenv("AWS_ACCESS_KEY_ID"))
print("Secret Key:", os.getenv("AWS_SECRET_ACCESS_KEY"))

Access Key: AKIATIZSLJ7LQ6ZDL6U3
Secret Key: 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

In [18]:
import boto3
import pandas as pd
from io import BytesIO

# AWS S3 setup
s3 = boto3.client('s3')
bucket = 'americasbreath123'
file_key = 'LLCP2018ASC/LLCP2018.ASC'

# Select only necessary columns and their widths
colspecs = [
    (0 ,2), (1402 ,1403), (87 ,88), (2064 ,2065), (2066 ,2067), (186 ,187), (203 ,205), (187 ,188), 
    (200 ,201), (1409 ,1415), (1455 ,1465), (1408 ,1409), (147 ,148), (140 ,141), (141 ,142), 
    (144 ,145), (224 ,225), (225 ,226), (226 ,227), (227 ,228), (112 ,113), (233 ,235), (107 ,109), 
    (110 ,111), (111 ,112), (109 ,110)
]

colnames = [
    "_STATE", "_URBSTAT", "SEXVAR", "_SEX", "_AGEG5YR", "EDUCA", "INCOME3", "RENTHOM1", "EMPLOY1",
    "_STSTR", "_WT2RAKE", "MSCODE", "HAVARTH4", "ASTHMA3", "ASTHNOW", "CHCCOPD3", "SMOKE100",
    "SMOKDAY2", "USENOW3", "ECIGNOW2", "EXERANY2", "AVEDRNK3", "PRIMINS1", "MEDCOST1", "CHECKUP1", "PERSDOC3"
]

In [ ]:
#Code to just pull 1 year of data without the loops

import boto3
import pandas as pd
from io import BytesIO

# --- Config ---
year = 2018
bucket_name = "americasbreath123"
asc_key = f"LLCP{year}.ASC"
parquet_key = f"LLCP{year}.parquet"

# --- AWS Session (assumes your credentials are set in env or config) ---
s3 = boto3.client("s3")

# --- Download .ASC file from S3 ---
response = s3.get_object(Bucket=bucket_name, Key=asc_key)
asc_content = response['Body'].read()

# --- Convert ASC to DataFrame ---
df = pd.read_fwf(BytesIO(asc_content), colspecs=colspecs, names=colnames)

# --- Convert DataFrame to Parquet in memory ---
parquet_buffer = BytesIO()
df.to_parquet(parquet_buffer, index=False)

# --- Upload Parquet to S3 ---
s3.put_object(Bucket=bucket_name, Key=parquet_key, Body=parquet_buffer.getvalue())

print(f"✅ {parquet_key} created and uploaded to S3 bucket {bucket_name}")

In [19]:
def process_and_upload_parquet(year):
    try: 
        file_key = f"LLCP{year}.ASC"
        parquet_key = f"parquet/LLCP{year}.parquet"
        
        print(f"Process year {year}...")
        
        #Get file from S3
        obj = s3.get_object(Bucket=bucket, Key=file_key)
        content = obj['Body'].read()

        # Convert to DataFrame
        df = pd.read_fwf(BytesIO(content), colspecs=colspecs, names=colnames)
        
        df["YEAR"] = year
        
        #Save to parquet in memory 
        buffer = BytesIO()
        df.to_parquet(buffer, index=False)
        buffer.seek(0)
        
        #Upload parquet file to S3
        s3.put_object(Bucket=bucket, Key=parquet_key, Body=buffer)
        print(f"Uploaded {parquet_key} to S3.")
        
    except Exception as e:
        print(f"Error processing year {year}: {e}")    
        
for yr in range(2018, 2024):
    process_and_upload_parquet(yr)

Process year 2018...
Error processing year 2018: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
Process year 2019...
Error processing year 2019: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
Process year 2020...
Error processing year 2020: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
Process year 2021...
Error processing year 2021: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
Process year 2022...
Error processing year 2022: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
Process year 2023...
Error processing year 2023: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

In [8]:
df.to_parquet("s3://americasbreath123/LLCP2018.parquet", engine="pyarrow")

In [9]:
import pandas as pd
import s3fs  # required to read directly from S3

df = pd.read_parquet('s3://americasbreath123/LLCP2018.parquet', engine='pyarrow')

In [10]:
df.head()

,_STATE,_URBSTAT,SEXVAR,_SEX,_AGEG5YR,EDUCA,INCOME3,RENTHOM1,EMPLOY1,_STSTR,...,SMOKE100,SMOKDAY2,USENOW3,ECIGNOW2,EXERANY2,AVEDRNK3,PRIMINS1,MEDCOST1,CHECKUP1,PERSDOC3
0,1,2.0,NaN,NaN,NaN,2.0,NaN,2.0,NaN,11011,...,2.0,1.0,5.0,2.0,2.0,NaN,1.0,2.0,1.0,2.0
1,1,1.0,NaN,NaN,NaN,2.0,80.0,2.0,0.0,11012,...,2.0,1.0,2.0,1.0,2.0,NaN,2.0,2.0,2.0,2.0
2,1,1.0,NaN,NaN,NaN,2.0,NaN,2.0,NaN,11011,...,7.0,9.0,NaN,7.0,1.0,NaN,2.0,2.0,2.0,2.0
3,1,1.0,NaN,NaN,NaN,2.0,NaN,2.0,NaN,11011,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0
4,1,1.0,NaN,NaN,NaN,2.0,NaN,2.0,NaN,11012,...,1.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0

In [11]:
df.columns

Index(['_STATE', '_URBSTAT', 'SEXVAR', '_SEX', '_AGEG5YR', 'EDUCA', 'INCOME3',
       'RENTHOM1', 'EMPLOY1', '_STSTR', '_WT2RAKE', 'MSCODE', 'HAVARTH4',
       'ASTHMA3', 'ASTHNOW', 'CHCCOPD3', 'SMOKE100', 'SMOKDAY2', 'USENOW3',
       'ECIGNOW2', 'EXERANY2', 'AVEDRNK3', 'PRIMINS1', 'MEDCOST1', 'CHECKUP1',
       'PERSDOC3'],
      dtype='object')

In [12]:
df

,_STATE,_URBSTAT,SEXVAR,_SEX,_AGEG5YR,EDUCA,INCOME3,RENTHOM1,EMPLOY1,_STSTR,...,SMOKE100,SMOKDAY2,USENOW3,ECIGNOW2,EXERANY2,AVEDRNK3,PRIMINS1,MEDCOST1,CHECKUP1,PERSDOC3
0,1,2.0,NaN,NaN,NaN,2.0,NaN,2.0,NaN,11011,...,2.0,1.0,5.0,2.0,2.0,NaN,1.0,2.0,1.0,2.0
1,1,1.0,NaN,NaN,NaN,2.0,80.0,2.0,0.0,11012,...,2.0,1.0,2.0,1.0,2.0,NaN,2.0,2.0,2.0,2.0
2,1,1.0,NaN,NaN,NaN,2.0,NaN,2.0,NaN,11011,...,7.0,9.0,NaN,7.0,1.0,NaN,2.0,2.0,2.0,2.0
3,1,1.0,NaN,NaN,NaN,2.0,NaN,2.0,NaN,11011,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0
4,1,1.0,NaN,NaN,NaN,2.0,NaN,2.0,NaN,11012,...,1.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437431,72,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,722019,...,1.0,1.0,5.0,7.0,2.0,NaN,1.0,2.0,2.0,2.0
437432,72,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,722019,...,5.0,2.0,NaN,2.0,2.0,NaN,2.0,2.0,2.0,2.0
437433,72,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,722019,...,3.0,1.0,3.0,2.0,2.0,NaN,2.0,2.0,1.0,2.0
437434,72,NaN,NaN,NaN,NaN,1.0,80.0,2.0,0.0,722019,...,1.0,1.0,5.0,7.0,2.0,NaN,12.0,2.0,1.0,2.0
437435,72,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN,722019,...,3.0,1.0,1.0,1.0,2.0,NaN,2.0,2.0,1.0,2.0